### PR TITLE
AFORM-4451: error when going to back next step on depend form

### PR DESCRIPTION
**Pull request by thachnd**
AFORM-4451

### CODE REVIEW

**Comment by quantranepiserver** [comment]
`actualValue` can be null or undefined, we should check null first
`actualValue?.toString()`

**Comment by quantranepiserver** [comment]
Why we merge into release branch ?

**Comment by thachnd** [comment]
> `actualValue` can be null or undefined, we should check null first `actualValue?.toString()`

the statement `!actualValue ? "" : getConcatString(actualValue.toString(), ",").toLocaleUpperCase();` already checked

**Comment by thachnd** [comment]
> Why we merge into release branch ?

This bug from testing the current release

**Review by quantranepiserver — APPROVED** [review]

**Pull request merged**
